version: "3.0"

networks:
  proxy:
    external: true
  jellyfin_default:
    external: true
  starr:
    external: true
  jellystat:
    external: true
  gluetun_network:
    external: true
      
services:
  # REVERSE PROXY IS IN OTHER DOCKER COMPOSE STACK

  #Jellyfin - used to display the media
  #This can also be replaced by Emby/Plex
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8096:8096
      - 8920:8920
    devices:
     - /dev/dri:/dev/dri #Required for jellyfin HW transcoding / QuickSync
    volumes:
      - ${BASE_PATH}/jellyfin/config:/config
      - ${MEDIA_SHARE}/media:/media
    restart: unless-stopped
    networks:
      - proxy
      - starr
    
  #Radarr - used to find movies automatically
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/radarr/config:/config
      - ${MEDIA_SHARE}:/data #Access to the entire /media
    ports:
      - 7878:7878
    networks:
      proxy:
      starr:
      gluetun_network:
        ipv4_address: ${RADARR_IPV4}
    restart: unless-stopped
    
  #Sonarr - used to find shows automatically
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/sonarr/config:/config
      - ${MEDIA_SHARE}:/data #Access to the entire /media
    ports:
      - 8989:8989
    networks:
      proxy:
      starr:
      gluetun_network:
        ipv4_address: ${SONARR_IPV4}
    restart: unless-stopped
  
  #Readarr - Used to download books
  readarr:
    image: lscr.io/linuxserver/readarr:0.4.19-nightly
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/readarr/config:/config
      - ${MEDIA_SHARE}:/data
    ports:
      - 8787:8787
    networks:
      - proxy
      - starr
    restart: unless-stopped
    
  #Lidarr - Used to download music 
  lidarr:
    image: blampe/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/lidarr/config:/config
      - ${MEDIA_SHARE}:/data
    ports:
      - 8686:8686
    networks:
      - proxy
      - starr
    restart: unless-stopped

  #Kapowarr - Used to download comics
  kapowarr:
    image: 'mrcas/kapowarr:latest'
    container_name: kapowarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/kapowarr/config:/app/db
      - ${MEDIA_SHARE}/temp_downloads:/app/temp_downloads
      - ${MEDIA_SHARE}:/data
    restart: unless-stopped
    
  #Prowlarr - manages your Sonarr, Radarr and download client
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/prowlarr/config:/config
    restart: unless-stopped
    
  #Autobrr - used to grab torrents using the trackers IRC channel - Increases seeding due to grabbing content before RSS feed
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    network_mode: "service:gluetun"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${BASE_PATH}/autobrr/config:/config

  #jellyseer - allows users to request media on their own
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/jellyseerr/config:/app/config
      - ${MEDIA_SHARE}:/data #Access to the entire ${BASE_PATH}
    networks:
      - proxy
      - starr
    ports:
      - 5055:5055
    restart: unless-stopped
    
  #Flaresolerr - Used as a proxy server to bypass Cloudflare and DDoS-GUARD protection.
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: alexfozor/flaresolverr:pr-1300-experimental
    container_name: flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
      - LANG=en_GB
      - DRIVER=nodriver
    restart: unless-stopped
      
  #Qbittorent - torrenting software
  #
  #You can also use RuTorrent, Transmisson or Deluge
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - TORRENTING_PORT=8694 #Make sure to port forward this port in your router so you can seed more effectively
      - UMASK=002
    volumes:
      - ${BASE_PATH}/qbittorent/config:/config
      - ${MEDIA_SHARE}:/data
    restart: unless-stopped

  #Tdarr - to transcode videos from one format to another like x265 or H.265
  #
  #This container requires a decent amount of horse power to run but will save space in the long run
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeName=ServerNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
    volumes:
      - ${BASE_PATH}/tdarr/server:/app/server
      - ${BASE_PATH}/tdarr/configs:/app/configs
      - ${BASE_PATH}/tdarr/logs:/app/logs
      - ${MEDIA_SHARE}:/data
      - ${TRANSCODE_PATH:-/transcode_cache}:/temp
    devices:
     - /dev/dri:/dev/dri #Required for HW transcoding /share QuickSync
    networks:
      - proxy
      
  #Bazarr - for subtitles. Try to use SRT format if you can rather than PGS due to performance issues
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${BASE_PATH}/bazarr/config:/config
      - ${MEDIA_SHARE}:/data
    ports:
      - 6767:6767
    networks:
      - starr
      - proxy
      
  #Cross Seed - used to take torrents from one tracker and seed them on another without leeching first. Increases ratio
  #
  #This is fairly advanced but can be removed if you don't think you will need it. Some trackers also don't allow this
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:latest
    container_name: cross-seed
    network_mode: "service:gluetun"
    user: ${PUID}:${PGID}
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${BASE_PATH}/cross-seed/config:/config #To configure you have to manually nano the config file
      - ${BASE_PATH}/qbittorent/config/qBittorrent/BT_backup:/torrents:ro # your torrent clients .torrent cache, can and should be mounted read-only (e.g. qbit: `BT_Backup` | deluge: `state` | transmission: `transmission/torrents` | rtorrent: session dir from `.rtorrent.rc`)
      - ${MEDIA_SHARE}/torrents/cross-seed:/data/cross-seeds
      # - ${MEDIA_SHARE}/cross-seed/current-cross-seeds:/data/cross-seeds # A place to temp save current cross seed .torrent files
      #- ${MEDIA_SHARE}/downloads:/data # OPTIONAL!!! this is dataDir path (for data-based matching) - will need to replicate your torrent client's container path (like Arr's do)
    command: daemon # this enables the search mode, change to daemon to specifically run the daemon
    
  #Wizarr - Allows you to create a share link that you can send to users to invite them to your media server
  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    restart: unless-stopped
    user: ${PUID}:${PGID}
    ports:
      - 5690:5690
    volumes:
      - ${BASE_PATH}/wizarr/data/database:/data/database
      - ${BASE_PATH}/wizarr/cache:/.cache
    networks:
      - proxy
      - starr
    environment:
      - APP_URL=${WIZARR_URL} #URL at which you will access and share 
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=${TZ} #Set your timezone here
      
  #Dozzle - Used to easily view logs of any container in real time!    
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    
  #Unpacker - Used to unzip zipped files
  unpackerr:
    image: ghcr.io/hotio/unpackerr:latest
    container_name: unpackerr
    volumes:
      # You need at least this one volume mapped so Unpackerr can find your files to extract.
      # Make sure this matches your Starr apps; the folder mount (/downloads or /data) should be identical.
      - ${MEDIA_SHARE}:/data
      - ${BASE_PATH}/unpackerr/config:/config
    restart: unless-stopped
    # What you see below are defaults for this compose. You only need to modify things specific to your environment.
    # Remove apps and feature configs you do not use or need. 
    # ie. Remove all lines that begin with UN_CMDHOOK, UN_WEBHOOK, UN_FOLDER, UN_WEBSERVER, and other apps you do not use.
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UN_START_DELAY=1m
      - UMASK=002
      - TZ=${TZ}
      #- UN_DEBUG=true
      # Sonarr Config
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${SONARR_KEY}
      #- UN_SONARR_0_PATHS_0=/${BASE_PATH}/downloads/shows
      - UN_SONARR_0_TIMEOUT=10s
      #- UN_SONARR_0_PATHS_0=/${BASE_PATH}/downloads/shows
      # Radarr Config
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${RADARR_KEY}
      #- UN_RADARR_0_PATHS_0=/${BASE_PATH}/downloads/movies
      - UN_RADARR_0_TIMEOUT=10s
      #- UN_RADARR_0_PATHS_0=/${BASE_PATH}/downloads/movies
    networks:
      - starr

  cabernet:
    image: ghcr.io/cabernetwork/cabernet:latest
    container_name: cabernet
    restart: unless-stopped
    volumes:
      - ${BASE_PATH}/cabernet/extensions:/app/plugins_ext
      - ${BASE_PATH}/cabernet/data:/app/data
    ports:
      - 5004:5004/tcp
      - 6077:6077/tcp
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - proxy
      
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADD}
      - SERVER_CITIES=${VPN_SERVER_CITIES}
      - UPDATER_PERIOD=24h
      - UPDATER_VPN_SERVICE_PROVIDERS=mullvad
      - WIREGUARD_MTU=${WIREGUARD_MTU:-1200}
      - PUBLICIP_API=${PUBLICIP_API}
      - PUBLICIP_API_TOKEN=${PUBLICIP_TOKEN}
    ports:
      - 2468:2468/tcp # cross-seed
      - 8080:8080/tcp # qBit
      - 8694:8694/tcp # qBit
      - 5656:5656/tcp # kapowarr
      - 8191:8191/tcp # flaresolverr
      - 9696:9696/tcp # prowlarr
      - 7474:7474 # autobrr
    networks:
      - starr
      - proxy
      - gluetun_network
    # IF VPN CANNOT CONNECT, USE BELOW COMMAND TO UPDATE SERVERS.
    # command: update -enduser -providers mullvad

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ${BASE_PATH}/homarr/configs:/app/data/configs
      - ${BASE_PATH}/homarr/icons:/app/public/icons
      - ${BASE_PATH}/homarr/data:/data
    ports:
      - 7575:7575
    networks:
      - proxy

  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: unless-stopped
    environment:
     TZ: ${TZ}
     PUID: ${PUID}
     PGID: ${PGID}
     ## General
     # TEST_RUN=True
     # SSL_VERIFICATION=False
     LOG_LEVEL: INFO
     ## Features 
     REMOVE_TIMER: 10
     REMOVE_FAILED: True
     REMOVE_FAILED_IMPORTS: True
     REMOVE_METADATA_MISSING: True
     REMOVE_MISSING_FILES: True
     REMOVE_ORPHANS: True
     REMOVE_SLOW: True
     REMOVE_STALLED: True
     REMOVE_UNMONITORED: True
     RUN_PERIODIC_RESCANS: '
        {
          "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7},
          "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}
        }'
     # Feature Settings
     PERMITTED_ATTEMPTS: 3
     NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
     MIN_DOWNLOAD_SPEED: 100     
     FAILED_IMPORT_MESSAGE_PATTERNS: '
        [
          "Not a Custom Format upgrade for existing", 
          "Not an upgrade for existing"
        ]'
     ## Radarr
     RADARR_URL: http://radarr:7878
     RADARR_KEY: $RADARR_KEY
     ## Sonarr
     SONARR_URL: http://sonarr:8989
     SONARR_KEY: $SONARR_KEY
     ## Lidarr
     LIDARR_URL: http://lidarr:8686
     LIDARR_KEY: $LIDARR_KEY
     ## Readarr
     READARR_URL: http://readarr:8787
     READARR_KEY: $READARR_KEY
     ## qBitorrent
     QBITTORRENT_URL: http://gluetun:8080
     QBITTORRENT_USERNAME: $QBIT_USER
     QBITTORRENT_PASSWORD: $QBIT_PASS
    networks:
      - starr
      - proxy

  jellystat-db:
    image: postgres:15.2
    container_name: jellystat-db
    environment:
      POSTGRES_DB: 'jfstat'
      POSTGRES_USER: ${JELLYSTATDB_USER:-postgres}
      POSTGRES_PASSWORD: ${JELLYSTATDB_PASS:-password}
    volumes:
      - ${BASE_PATH}/jellystat/postgres-data:/var/lib/postgresql/data # Mounting the volume
    restart: unless-stopped
    networks:
      - jellystat

  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: jellystat
    environment:
      POSTGRES_USER: ${JELLYSTATDB_USER:-postgres}
      POSTGRES_PASSWORD: ${JELLYSTATDB_PASS:-password}
      POSTGRES_IP: jellystat-db
      POSTGRES_PORT: 5432
      JWT_SECRET: ${JWT_SECRET:-'my-secret-jwt-key'}
    ports:
      - 3000:3000 #Server Port
    volumes:
      - ${BASE_PATH}/jellystat/postgres-backup:/app/backend/backup-data # Mounting the volume
    depends_on:
      - jellystat-db
    restart: unless-stopped
    networks:
      - jellystat
      - proxy

    decluttarr:
      image: ghcr.io/manimatter/decluttarr:latest
      container_name: decluttarr
      restart: always
      environment:
        TZ: Europe/Zurich
        PUID: 1000
        PGID: 1000

        LOG_LEVEL: INFO
        TEST_RUN: True
        TIMER: 10
        # IGNORED_DOWNLOAD_CLIENTS: >
        #   - emulerr
        # SSL_VERIFICATION: true
        # PRIVATE_TRACKER_HANDLING: "obsolete_tag"
        # PUBLIC_TRACKER_HANDLING: "remove"
        # OBSOLETE_TAG: "Obsolete"
        # PROTECTED_TAG: "Keep"

        # # --- Optional: Job Defaults ---
        # You can use these to set those parameters across all jobs. If you don't specify it here, the defaults set by system will be used
        # If you set job-specific parameters (further down below), they will override these settings.
        # max_strikes: 3
        # MIN_DAYS_BETWEEN_SEARCHES: 7
        # MAX_CONCURRENT_SEARCHES: 3

        # # --- Jobs (short notation) ---
        # If you want to go with the most basic settings, you can just turn them all on:
        REMOVE_BAD_FILES: True
        REMOVE_FAILED_DOWNLOADS: True
        REMOVE_FAILED_IMPORTS: True
        REMOVE_METADATA_MISSING: True
        REMOVE_MISSING_FILES: True
        REMOVE_ORPHANS: True
        REMOVE_SLOW: True
        REMOVE_STALLED: True
        REMOVE_UNMONITORED: True
        SEARCH_BETTER: True
        SEARCH_MISSING: True
        DETECT_DELETIONS: True

        # # --- OR: Jobs (with job-specific settings) ---
        # Alternatively, you can use the below notation, which for certain jobs allows you to set additional parameters
        # As written above, these can also be set as Job Defaults so you don't have to specify them as granular as below.
        # REMOVE_BAD_FILES: |
        #   keep_archives: True
        # REMOVE_FAILED_DOWNLOADS: True
        # REMOVE_FAILED_IMPORTS: |
        #   message_patterns:
        #     - "Not a Custom Format upgrade for existing*"
        #     - "Not an upgrade for existing*"
        #     - "*Found potentially dangerous file with extension*"
        #     - "Invalid video file*"
        #     - "No files found are eligible for import*"
        #     - "One or more episodes expected in this release were not imported or missing from the release"
        # REMOVE_METADATA_MISSING: |
        #   max_strikes: 3
        # REMOVE_MISSING_FILES: True
        # REMOVE_ORPHANS: True
        # REMOVE_SLOW: |
        #   min_speed: 100
        #   max_strikes: 3
        # REMOVE_STALLED: |
        #   max_strikes: 3
        # REMOVE_UNMONITORED: True
        # SEARCH_UNMET_CUTOFF: |
        #   min_days_between_searches: 7
        #   max_concurrent_searches: 3
        # SEARCH_MISSING: |
        #   min_days_between_searches: 7
        #   max_concurrent_searches: 3
        # DETECT_DELETIONS:

        # --- Instances ---
        SONARR: >
          - base_url: "http://sonarr1:8989"
            api_key: "$SONARR_API_KEY"
          - base_url: "http://sonarr2:8989"
            api_key: "$SONARR_API_KEY"

        # RADARR: >
        #   - base_url: "http://radarr:7878"
        #     api_key: "$RADARR_API_KEY"

        # READARR: >
        #   - base_url: "http://readarr:8787"
        #     api_key: "$READARR_API_KEY"

        # LIDARR: >
        #   - base_url: "http://lidarr:8686"
        #     api_key: "$LIDARR_API_KEY"

        # WHISPARR: >
        #   - base_url: "http://whisparr:6969"
        #     api_key: "$WHISPARR_API_KEY"

        # --- Download Clients ---
        QBITTORRENT: >
          - base_url: "http://qbittorrent:8080"
            # username: "$QBIT_USERNAME" # (optional -> if not provided, assuming not needed)
            # password: "$QBIT_PASSWORD" # (optional -> if not provided, assuming not needed)
            name: "qBittorrent 1" # (optional -> if not provided, assuming "qBittorrent". Must correspond with what is specified in your *arr as download client name)
          - base_url: "http://qbittorrent:8080"
            name: "qBittorrent 2" 
      volumes:
        # - $DOCKERDIR/appdata/decluttarr/logs:/app/logs # Uncomment to get logs in text file, too      
        # - $DATADIR/media:/media # If you use detect_deletions, add the identical mount paths that you use in your sonarr/radarr instances. This may be different to this example!



    
    janitorr:
      container_name: janitorr
      image: ghcr.io/schaka/janitorr:stable
      user: ${PUID}:${PGID} # Replace with your user who should own your application.yml file
      volumes:
        - ${BASE_PATH}/janitorr/application.yml:/workspace/application.yml
        - ${BASE_PATH}/janitorr/logs:/logs
        - ${MEDIA_SHARE}:/data
      healthcheck:
        test: "wget -T5 -qO- http://localhost:8081/health | grep UP || exit 1"
        start_period: 30s
        interval: 5s
        retries: 3
      networks:
        - starr

    

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    ports:
      - 6868:6868
    volumes:
      - ${BASE_PATH}/profilarr:/config
    environment:
      - TZ=${TZ} # Set your timezone
    restart: unless-stopped
    networks:
      - starr
