#!/bin/bash
# Modular Server Setup Script
#
# Flow:
#   1. Source all module scripts (functions only — no side effects)
#   2. Set defaults
#   3. Load existing config, or run first-time wizard
#   4. Main menu: edit any section, validate, then apply
#
# Usage:
#   sudo ./setup.sh               # interactive
#   sudo ./setup.sh -c /path/to/server-setup.conf  # load specific config

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root." >&2
    exit 1
fi

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${DIR}/server-setup.conf"

# ── Source module scripts ─────────────────────────────────────────────────────
# validate-config.sh must come first — it defines get_manager_ports() which
# is used by network-config.sh, container-manager-config.sh, etc.
source "${DIR}/validate-config.sh"
source "${DIR}/user-config.sh"
source "${DIR}/ssh-config.sh"
source "${DIR}/network-config.sh"
source "${DIR}/sources-list.sh"
source "${DIR}/docker-config.sh"
source "${DIR}/podman-config.sh"
source "${DIR}/container-engine-config.sh"
source "${DIR}/container-manager-config.sh"
source "${DIR}/security-config.sh"
source "${DIR}/choose-container-options.sh"

# ── Defaults ─────────────────────────────────────────────────────────────────
ADMIN_USER=""
CREATE_ADMIN_USER=0

SSH_PORT=22
AUTH_METHODS="publickey"
PERMIT_ROOT_LOGIN="no"
GENERATE_SSH_KEYPAIR="yes"
SSH_PUBKEY=""

EXTRA_OPEN_PORTS=""

EXTRA_PACKAGES="micro tmux fzf btop git sudo net-tools iputils-ping rsync bash-completion nmap lynis"
INSTALL_RCLONE="no"

CONTAINER_ENGINE="docker"
PODMAN_SOURCE="github"
CONTAINER_MANAGER="portainer"

SECURITY_HARDENING="yes"
SECURITY_FAIL2BAN="yes"
SECURITY_APPARMOR="yes"
SECURITY_AUDITD="yes"
SECURITY_AIDE="no"
SECURITY_AUTO_UPDATES="yes"

# ── Config I/O ────────────────────────────────────────────────────────────────
load_config() {
    if [[ -f "$CONFIG_FILE" ]]; then
        # shellcheck disable=SC1090
        source "$CONFIG_FILE"
        echo "Loaded config: $CONFIG_FILE"
        return 0
    fi
    return 1
}

write_config() {
    cat > "$CONFIG_FILE" << EOF
# Server Setup Config — generated by setup.sh on $(date)

# === User ===
ADMIN_USER="${ADMIN_USER}"
CREATE_ADMIN_USER=${CREATE_ADMIN_USER}

# === SSH ===
SSH_PORT=${SSH_PORT}
AUTH_METHODS="${AUTH_METHODS}"
PERMIT_ROOT_LOGIN="${PERMIT_ROOT_LOGIN}"
GENERATE_SSH_KEYPAIR="${GENERATE_SSH_KEYPAIR}"
SSH_PUBKEY="${SSH_PUBKEY}"

# === Network ===
EXTRA_OPEN_PORTS="${EXTRA_OPEN_PORTS}"

# === Packages ===
EXTRA_PACKAGES="${EXTRA_PACKAGES}"
INSTALL_RCLONE="${INSTALL_RCLONE}"

# === Container Engine ===
CONTAINER_ENGINE="${CONTAINER_ENGINE}"
PODMAN_SOURCE="${PODMAN_SOURCE}"

# === Container Manager ===
CONTAINER_MANAGER="${CONTAINER_MANAGER}"

# === Security Hardening ===
SECURITY_HARDENING="${SECURITY_HARDENING}"
SECURITY_FAIL2BAN="${SECURITY_FAIL2BAN}"
SECURITY_APPARMOR="${SECURITY_APPARMOR}"
SECURITY_AUDITD="${SECURITY_AUDITD}"
SECURITY_AIDE="${SECURITY_AIDE}"
SECURITY_AUTO_UPDATES="${SECURITY_AUTO_UPDATES}"
EOF
    echo "Config saved: $CONFIG_FILE"
}

# ── Overview ──────────────────────────────────────────────────────────────────
show_overview() {
    local manager_ports
    manager_ports="$(get_manager_ports "$CONTAINER_MANAGER")"
    local pub_key_status="none"
    [[ -n "$SSH_PUBKEY" ]]           && pub_key_status="provided"
    [[ "$GENERATE_SSH_KEYPAIR" == "yes" ]] && pub_key_status="generate (ed25519)"

    echo ""
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║                 Configuration Overview                  ║"
    echo "╠══════════════════════╦═══════════════════════════════════╣"
    printf "║  %-20s║  %-33s║\n" "User"             "${ADMIN_USER:-<not set>} (create: ${CREATE_ADMIN_USER})"
    echo "╠══════════════════════╬═══════════════════════════════════╣"
    printf "║  %-20s║  %-33s║\n" "SSH Port"         "${SSH_PORT}"
    printf "║  %-20s║  %-33s║\n" "Auth Methods"     "${AUTH_METHODS}"
    printf "║  %-20s║  %-33s║\n" "Permit Root"      "${PERMIT_ROOT_LOGIN}"
    printf "║  %-20s║  %-33s║\n" "SSH Key"          "${pub_key_status}"
    echo "╠══════════════════════╬═══════════════════════════════════╣"
    printf "║  %-20s║  %-33s║\n" "Container Engine" "${CONTAINER_ENGINE}"
    if [[ "$CONTAINER_ENGINE" == podman* ]]; then
        printf "║  %-20s║  %-33s║\n" "Podman Source"  "${PODMAN_SOURCE}"
    fi
    printf "║  %-20s║  %-33s║\n" "Manager"          "${CONTAINER_MANAGER}"
    if [[ -n "$manager_ports" ]]; then
        printf "║  %-20s║  %-33s║\n" "Manager Port(s)" "${manager_ports}"
    fi
    echo "╠══════════════════════╬═══════════════════════════════════╣"
    printf "║  %-20s║  %-33s║\n" "Sec. Hardening"   "${SECURITY_HARDENING}"
    printf "║  %-20s║  %-33s║\n" "  Fail2ban"       "${SECURITY_FAIL2BAN}"
    printf "║  %-20s║  %-33s║\n" "  AppArmor"       "${SECURITY_APPARMOR}"
    printf "║  %-20s║  %-33s║\n" "  Auditd"         "${SECURITY_AUDITD}"
    printf "║  %-20s║  %-33s║\n" "  AIDE"           "${SECURITY_AIDE}"
    printf "║  %-20s║  %-33s║\n" "  Auto-updates"   "${SECURITY_AUTO_UPDATES}"
    echo "╠══════════════════════╬═══════════════════════════════════╣"
    printf "║  %-20s║  %-33s║\n" "Rclone"           "${INSTALL_RCLONE}"
    printf "║  %-20s║  %-33s║\n" "Extra Ports"      "${EXTRA_OPEN_PORTS:-<none>}"
    echo "╚══════════════════════╩═══════════════════════════════════╝"
    echo ""
}

# ── Package prompt ────────────────────────────────────────────────────────────
prompt_packages() {
    local inp
    echo ""
    echo "=== Package Configuration ==="
    echo "  Current extra packages:"
    echo "    ${EXTRA_PACKAGES}"
    read -r -p "  Edit package list (or Enter to keep): " inp
    [[ -n "$inp" ]] && EXTRA_PACKAGES="$inp"

    read -r -p "  Install rclone? (yes/no) [${INSTALL_RCLONE}]: " inp
    case "${inp:-$INSTALL_RCLONE}" in
        y|yes|Yes|YES) INSTALL_RCLONE="yes" ;;
        n|no|No|NO)    INSTALL_RCLONE="no"  ;;
    esac
}

# ── Apply all ─────────────────────────────────────────────────────────────────
apply_all() {
    echo ""
    echo "╔══════════════════════════════════════════════╗"
    echo "║            Applying Configuration            ║"
    echo "╚══════════════════════════════════════════════╝"

    # 1 — System update
    echo ""
    echo "[ 1/7 ] Updating system packages..."
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get -y -qq upgrade

    # 2 — Base packages
    echo ""
    echo "[ 2/7 ] Installing packages..."
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        curl wget ca-certificates gnupg ufw
    # shellcheck disable=SC2086
    DEBIAN_FRONTEND=noninteractive apt-get install -y $EXTRA_PACKAGES
    [[ "$INSTALL_RCLONE" == "yes" ]] && apt-get install -y rclone

    # 3 — User
    echo ""
    echo "[ 3/7 ] Configuring user..."
    apply_user_config

    # 4 — SSH
    echo ""
    echo "[ 4/7 ] Configuring SSH..."
    apply_ssh_config \
        "$SSH_PORT" "$ADMIN_USER" "$AUTH_METHODS" \
        "$PERMIT_ROOT_LOGIN" "$SSH_PUBKEY" "$GENERATE_SSH_KEYPAIR"

    # 5 — Firewall
    echo ""
    echo "[ 5/7 ] Configuring firewall..."
    apply_firewall "$SSH_PORT" "$CONTAINER_MANAGER" "$EXTRA_OPEN_PORTS"

    # 6 — Container engine
    echo ""
    echo "[ 6/7 ] Installing container engine (${CONTAINER_ENGINE})..."
    case "$CONTAINER_ENGINE" in
        docker)
            install_docker
            usermod -aG docker "$ADMIN_USER"
            ;;
        docker-rootless)
            install_docker_rootless "$ADMIN_USER"
            ;;
        podman)
            apply_podman_install "$PODMAN_SOURCE"
            ;;
        podman-rootless)
            apply_podman_install "$PODMAN_SOURCE"
            setup_podman_rootless "$ADMIN_USER"
            ;;
        *)
            echo "  Unknown container engine: ${CONTAINER_ENGINE}" >&2
            ;;
    esac

    # 7 — Container manager
    echo ""
    if [[ "${CONTAINER_MANAGER:-none}" != "none" ]]; then
        echo "[ 7/7 ] Installing container manager (${CONTAINER_MANAGER})..."
        install_container_manager "$CONTAINER_MANAGER" "$CONTAINER_ENGINE" "$ADMIN_USER"
    else
        echo "[ 7/7 ] No container manager selected — skipping."
    fi

    # + — Security hardening
    echo ""
    echo "[ +  ] Applying security hardening..."
    apply_security_hardening

    # ── Summary ──────────────────────────────────────────────────────────────
    echo ""
    show_overview

    echo "══════════════════════════════════════════════════════════"
    echo "  IMPORTANT — Save the following information"
    echo "══════════════════════════════════════════════════════════"
    echo "  Admin user : ${ADMIN_USER}"
    echo "  SSH port   : ${SSH_PORT}"
    echo "  Auth       : ${AUTH_METHODS}"

    local key_file="/home/${ADMIN_USER}/.ssh/id_ed25519"
    if [[ -f "$key_file" ]]; then
        echo ""
        echo "  SSH Private Key (save this NOW — it is not stored elsewhere):"
        echo "  ─────────────────────────────────────────────────────────────"
        cat "$key_file"
        echo "  ─────────────────────────────────────────────────────────────"
        echo "  Public key:"
        cat "${key_file}.pub"
    fi
    echo ""

    read -r -p "Reboot now to apply kernel/sysctl changes? (yes/no): " REBOOT1
    if [[ "${REBOOT1,,}" == "yes" ]]; then
        read -r -p "Confirm reboot (yes/no): " REBOOT2
        [[ "${REBOOT2,,}" == "yes" ]] && reboot || echo "Reboot canceled."
    else
        echo "Please reboot later to finalize all changes."
    fi
}

# ── First-time wizard ─────────────────────────────────────────────────────────
run_wizard() {
    echo ""
    echo "╔══════════════════════════════════════════════╗"
    echo "║       Server Setup Wizard (first run)        ║"
    echo "╚══════════════════════════════════════════════╝"

    prompt_user_config
    prompt_ssh_config
    prompt_container_engine
    prompt_container_manager
    prompt_network_config
    prompt_packages
    prompt_security_config

    write_config
    echo ""
    echo "Initial configuration saved."
    echo "Review the overview, resolve any validation issues, then select [9] to apply."
}

# ── Main menu ─────────────────────────────────────────────────────────────────
main_menu() {
    local sel

    while true; do
        show_overview
        validate_config || true   # show issues without exiting

        echo ""
        echo "  ─── Menu ──────────────────────────────"
        echo "  1) Edit user configuration"
        echo "  2) Edit SSH settings"
        echo "  3) Edit container engine"
        echo "  4) Edit container manager"
        echo "  5) Edit firewall / extra ports"
        echo "  6) Edit packages"
        echo "  7) Edit security options"
        echo "  8) Save config to file"
        echo "  9) Apply installation"
        echo "  0) Exit without changes"
        echo "  ────────────────────────────────────────"
        read -r -p "  Select (0-9): " sel

        case "$sel" in
            1) prompt_user_config ;;
            2) prompt_ssh_config ;;
            3) prompt_container_engine ;;
            4) prompt_container_manager ;;
            5) prompt_network_config ;;
            6) prompt_packages ;;
            7) prompt_security_config ;;
            8) write_config ;;
            9)
                if ! validate_config; then
                    echo ""
                    echo "  [ERROR] Configuration has errors — resolve them before applying."
                    suggest_fixes
                    read -r -p "  Press Enter to return to the menu..." _ignore
                else
                    write_config
                    apply_all
                    break
                fi
                ;;
            0) echo "Exiting without changes."; exit 0 ;;
            *) echo "  Invalid option — enter 0-9." ;;
        esac
    done
}

# ── Entry point ───────────────────────────────────────────────────────────────
[[ "${1:-}" == "-c" && -n "${2:-}" ]] && CONFIG_FILE="$2"

if ! load_config; then
    echo "No existing config found — starting first-time wizard."
    run_wizard
fi

main_menu
