version: "3"
services:
  autobrr:
    container_name: autobrr
    hostname: autobrr
    network_mode: "service:gluetun"
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}                           # Timezone, using variable from .env file
      # Optional configuration options:
      # - PUID=1000                        # Optional user ID (default uses 1000)
      # - PGID=1000                        # Optional group ID (default uses 1000)
      # - AUTOBRR_HOST=0.0.0.0             # Host address to bind to
      # - AUTOBRR_PORT=7474                # Web UI port
      # - AUTOBRR_LOG_LEVEL=INFO           # Log level (ERROR, WARN, INFO, DEBUG, TRACE)
      # - AUTOBRR_DB_PATH=/config/autobrr.db  # Database path
    user: 1000:1000                        # Set user:group for permissions
    volumes:
      - ${BASE_DOCKER_DATA_PATH}/autobrr/config:/config  # Config directory
    ports:
      - 7474:7474                          # WebUI port


services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    #logging:
    #  driver: json-file
    #  options:
    #    max-file: ${DOCKERLOGGING_MAXFILE}
    #    max-size: ${DOCKERLOGGING_MAXSIZE}
    user: 1000:1000
    environment:
      - TZ=${TZ}
    volumes:
      - ${BASE_DOCKER_DATA_PATH}/autobrr/config:/config
    ports:
      - 7474:7474


      Enviroment Variables
      services:
  autobrr:
    environment:
      - AUTOBRR__HOST=string
      - AUTOBRR__PORT=string
      - AUTOBRR__BASE_URL=string
      - AUTOBRR__LOG_LEVEL=string
      - AUTOBRR__LOG_PATH=string
      - AUTOBRR__LOG_MAX_SIZE=string/int without MB
      - AUTOBRR__LOG_MAX_BACKUPS=string/int
      - AUTOBRR__SESSION_SECRET=string
      - AUTOBRR__CUSTOM_DEFINITIONS=string
      - AUTOBRR__CHECK_FOR_UPDATES=bool
      - AUTOBRR__DATABASE_TYPE=sqlite/postgres
      - AUTOBRR__POSTGRES_HOST=string
      - AUTOBRR__POSTGRES_PORT=string
      - AUTOBRR__POSTGRES_DATABASE=string
      - AUTOBRR__POSTGRES_USER=string
      - AUTOBRR__POSTGRES_PASS=string
      - AUTOBRR__POSTGRES_SSLMODE=string
      - AUTOBRR__POSTGRES_EXTRA_PARAMS=string
      - AUTOBRR__OIDC_ENABLED=bool
      - AUTOBRR__OIDC_ISSUER=string
      - AUTOBRR__OIDC_CLIENT_ID=string
      - AUTOBRR__OIDC_CLIENT_SECRET=string
      - AUTOBRR__OIDC_REDIRECT_URL=string
      - AUTOBRR__OIDC_DISABLE_BUILT_IN_LOGIN=bool
      - AUTOBRR__METRICS_ENABLED=bool
      - AUTOBRR__METRICS_HOST=string
      - AUTOBRR__METRICS_PORT=int
      - AUTOBRR__METRICS_BASIC_AUTH_USERS=string