#!/usr/bin/env bash
# =============================================================================
# REVERSE PROXY CONFIGURATOR
# =============================================================================
# Generate reverse proxy configuration for services that expose HTTP, based on
# registry/services.json.
#
# Supports three backends:
#   godoxy  — proxy.* Docker labels
#   traefik — traefik.* Docker labels + Traefik dynamic config YAML
#   caddy   — Caddyfile snippet + caddy Docker Compose service
#
# Output:
#   stacks/proxy-<backend>.yaml   Docker Compose overlay with labels
#   docs/PROXY-SETUP.md           Human-readable setup guide
#   stacks/Caddyfile              (caddy only)
#   stacks/traefik-dynamic.yaml   (traefik only)
#
# Dependencies: bash ≥4, jq, awk, sed
#
# Usage:
#   bash scripts/reverse-proxy-configurator.sh --backend godoxy
#   bash scripts/reverse-proxy-configurator.sh --backend traefik --domain example.com
#   bash scripts/reverse-proxy-configurator.sh --backend caddy
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
REGISTRY="${REPO_ROOT}/registry/services.json"
STACKS_DIR="${REPO_ROOT}/stacks"
DOCS_DIR="${REPO_ROOT}/docs"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

die()  { echo -e "${RED}ERROR:${RESET} $*" >&2; exit 1; }
warn() { echo -e "${YELLOW}WARNING:${RESET} $*" >&2; }
info() { echo -e "${CYAN}  →${RESET} $*"; }

# ─── Arg parsing ─────────────────────────────────────────────────────────────
BACKEND="godoxy"
DOMAIN="\${BASE_DOMAIN}"

usage() {
    grep '^#' "${BASH_SOURCE[0]}" | grep -v '^#!/' | sed 's/^# \{0,1\}//'
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --backend) BACKEND="$2"; shift 2 ;;
        --domain)  DOMAIN="$2";  shift 2 ;;
        -h|--help) usage ;;
        *) die "Unknown argument: $1" ;;
    esac
done

case "${BACKEND}" in
    godoxy|traefik|caddy) ;;
    *) die "Invalid backend '${BACKEND}'. Choose: godoxy, traefik, caddy" ;;
esac

# ─── Dependency check ────────────────────────────────────────────────────────
command -v jq &>/dev/null || die "jq is required. Install: sudo apt install jq"
[[ -f "${REGISTRY}" ]] || die "Registry not found: ${REGISTRY}"
mkdir -p "${STACKS_DIR}" "${DOCS_DIR}"

# ─── Load HTTP-exposing services ─────────────────────────────────────────────
echo -e "\n${BOLD}Loading HTTP services from registry …${RESET}"

declare -a SVR_NAMES=()
declare -a SVR_HOSTS=()
declare -a SVR_PORTS=()
declare -a SVR_DESCS=()
declare -a SVR_PATHS=()

while IFS=$'\t' read -r name host hc_url desc rel_path; do
    # Extract port from healthcheck URL  http://host:PORT/path
    port="80"
    if [[ "${hc_url}" =~ :([0-9]+) ]]; then
        port="${BASH_REMATCH[1]}"
    fi
    # Resolve domain placeholder
    host="${host//\$\{BASE_DOMAIN\}/${DOMAIN}}"
    SVR_NAMES+=("${name}")
    SVR_HOSTS+=("${host}")
    SVR_PORTS+=("${port}")
    SVR_DESCS+=("${desc}")
    SVR_PATHS+=("${rel_path}")
done < <(jq -r '
    .services[]
    | select(.exposes_http == true)
    | [
        .name,
        (.reverse_proxy.host // (.name + ".${BASE_DOMAIN}")),
        (.healthcheck.url // ""),
        (.description // ""),
        (.path // "")
      ]
    | @tsv
' "${REGISTRY}")

count="${#SVR_NAMES[@]}"
echo "  Found ${count} HTTP-exposing service(s)."
[[ "${count}" -eq 0 ]] && die "No HTTP-exposing services found. Check exposes_http fields in registry."

# ─── godoxy ──────────────────────────────────────────────────────────────────
generate_godoxy() {
    local out="${STACKS_DIR}/proxy-godoxy.yaml"
    {
        echo "# GODOXY PROXY OVERLAY"
        echo "# Generated by scripts/reverse-proxy-configurator.sh --backend godoxy"
        echo "# Apply after your service stacks are running."
        echo "# Requires godoxy running on the same Docker network."
        echo ""
        echo "services:"
        local i
        for (( i=0; i<count; i++ )); do
            local name="${SVR_NAMES[$i]}"
            local host="${SVR_HOSTS[$i]}"
            local port="${SVR_PORTS[$i]}"
            local rel="${SVR_PATHS[$i]}"
            echo "  ${name}:"
            echo "    # Source: ${rel}"
            echo "    labels:"
            echo "      proxy.host: \"${host}\""
            echo "      proxy.port: \"${port}\""
            echo "      proxy.scheme: \"http\""
            echo "    networks:"
            echo "      - \${DEFAULT_NETWORK}"
            echo ""
        done
        echo "networks:"
        echo "  \${DEFAULT_NETWORK}:"
        echo "    external: true"
    } > "${out}"
    info "Written: ${out#"${REPO_ROOT}/"}"
}

# ─── traefik ─────────────────────────────────────────────────────────────────
generate_traefik() {
    local out="${STACKS_DIR}/proxy-traefik.yaml"
    local dyn="${STACKS_DIR}/traefik-dynamic.yaml"

    # Compose overlay
    {
        echo "# TRAEFIK LABEL OVERLAY"
        echo "# Generated by scripts/reverse-proxy-configurator.sh --backend traefik"
        echo ""
        echo "services:"
        local i
        for (( i=0; i<count; i++ )); do
            local name="${SVR_NAMES[$i]}"
            local host="${SVR_HOSTS[$i]}"
            local port="${SVR_PORTS[$i]}"
            local rel="${SVR_PATHS[$i]}"
            echo "  ${name}:"
            echo "    # Source: ${rel}"
            echo "    labels:"
            echo "      traefik.enable: \"true\""
            echo "      traefik.http.routers.${name}.rule: \"Host(\`${host}\`)\""
            echo "      traefik.http.routers.${name}.entrypoints: \"websecure\""
            echo "      traefik.http.routers.${name}.tls.certresolver: \"letsencrypt\""
            echo "      traefik.http.services.${name}.loadbalancer.server.port: \"${port}\""
            echo "    networks:"
            echo "      - \${DEFAULT_NETWORK}"
            echo ""
        done
        echo "networks:"
        echo "  \${DEFAULT_NETWORK}:"
        echo "    external: true"
    } > "${out}"
    info "Written: ${out#"${REPO_ROOT}/"}"

    # Dynamic config
    {
        echo "# TRAEFIK DYNAMIC CONFIGURATION"
        echo "# Generated by scripts/reverse-proxy-configurator.sh --backend traefik"
        echo "# Mount this file into Traefik's dynamic configuration directory."
        echo ""
        echo "http:"
        echo "  routers:"
        local i
        for (( i=0; i<count; i++ )); do
            local name="${SVR_NAMES[$i]}"
            local host="${SVR_HOSTS[$i]}"
            echo "    ${name}:"
            echo "      rule: \"Host(\`${host}\`)\""
            echo "      entryPoints:"
            echo "        - websecure"
            echo "      service: ${name}"
            echo "      tls:"
            echo "        certResolver: letsencrypt"
        done
        echo "  services:"
        for (( i=0; i<count; i++ )); do
            local name="${SVR_NAMES[$i]}"
            local port="${SVR_PORTS[$i]}"
            echo "    ${name}:"
            echo "      loadBalancer:"
            echo "        servers:"
            echo "          - url: \"http://${name}:${port}\""
        done
    } > "${dyn}"
    info "Written: ${dyn#"${REPO_ROOT}/"}"
}

# ─── caddy ────────────────────────────────────────────────────────────────────
generate_caddy() {
    local caddyfile="${STACKS_DIR}/Caddyfile"
    local out="${STACKS_DIR}/proxy-caddy.yaml"
    local now
    now="$(date -u '+%Y-%m-%d %H:%M:%S UTC')"

    {
        echo "# Caddyfile — generated by scripts/reverse-proxy-configurator.sh --backend caddy"
        echo "# Domain: ${DOMAIN}"
        echo "# Generated: ${now}"
        echo ""
        local i
        for (( i=0; i<count; i++ )); do
            local name="${SVR_NAMES[$i]}"
            local host="${SVR_HOSTS[$i]}"
            local port="${SVR_PORTS[$i]}"
            local desc="${SVR_DESCS[$i]}"
            echo "${host} {"
            echo "    reverse_proxy ${name}:${port}"
            [[ -n "${desc}" ]] && echo "    # ${desc}"
            echo "}"
            echo ""
        done
    } > "${caddyfile}"
    info "Written: ${caddyfile#"${REPO_ROOT}/"}"

    {
        echo "# CADDY COMPOSE SERVICE"
        echo "# Generated by scripts/reverse-proxy-configurator.sh --backend caddy"
        echo ""
        echo "services:"
        echo "  caddy:"
        echo "    image: caddy:latest"
        echo "    container_name: caddy"
        echo "    restart: unless-stopped"
        echo "    ports:"
        echo "      - \${PORT_CADDY_HTTP:-80}:80"
        echo "      - \${PORT_CADDY_HTTPS:-443}:443"
        echo "    volumes:"
        echo "      - ./Caddyfile:/etc/caddy/Caddyfile:ro"
        echo "      - \${DOCKER_DATA}/caddy/data:/data"
        echo "      - \${DOCKER_DATA}/caddy/config:/config"
        echo "    networks:"
        echo "      - \${DEFAULT_NETWORK}"
        echo ""
        echo "networks:"
        echo "  \${DEFAULT_NETWORK}:"
        echo "    external: true"
    } > "${out}"
    info "Written: ${out#"${REPO_ROOT}/"}"
}

# ─── docs/PROXY-SETUP.md ──────────────────────────────────────────────────────
generate_doc() {
    local out="${DOCS_DIR}/PROXY-SETUP.md"
    local now
    now="$(date -u '+%Y-%m-%d')"
    {
        echo "# Reverse Proxy Setup"
        echo ""
        echo "> Generated ${now} by \`scripts/reverse-proxy-configurator.sh\`  "
        echo "> Backend: **${BACKEND}** | Domain: **${DOMAIN}**"
        echo ""
        echo "## Services exposed via reverse proxy"
        echo ""
        echo "| Service | Host | Port | Description |"
        echo "|---------|------|------|-------------|"
        local i
        for (( i=0; i<count; i++ )); do
            echo "| ${SVR_NAMES[$i]} | \`${SVR_HOSTS[$i]}\` | ${SVR_PORTS[$i]} | ${SVR_DESCS[$i]} |"
        done
        echo ""
        echo "## Quick Start"
        echo ""
        echo "1. Copy \`stacks/proxy-${BACKEND}.yaml\` to your deployment directory."
        echo "2. Ensure your \`.env\` has \`BASE_DOMAIN\` and \`DEFAULT_NETWORK\` set."
        echo "3. Start the proxy overlay:"
        echo ""
        echo '```bash'
        echo "docker compose -f stacks/proxy-${BACKEND}.yaml up -d"
        echo '```'
        echo ""
        echo "## Backend notes"
        echo ""
        case "${BACKEND}" in
            godoxy)
                echo "### godoxy"
                echo "Labels use the \`proxy.*\` namespace. Ensure godoxy runs on \`\${DEFAULT_NETWORK}\`."
                ;;
            traefik)
                echo "### Traefik"
                echo "Labels are injected inline per service. Mount \`traefik-dynamic.yaml\` into"
                echo "Traefik's \`providers.file\` directory for file-provider routing."
                echo ""
                echo "Traefik service definition: see \`stacks/traefik.yaml\` (if created by setup)."
                ;;
            caddy)
                echo "### Caddy"
                echo "The generated \`Caddyfile\` is mounted read-only into the Caddy container."
                echo "Edit \`${STACKS_DIR}/Caddyfile\` to customise routes."
                ;;
        esac
        echo ""
        echo "## Security recommendations"
        echo ""
        echo "- Set \`BASE_DOMAIN\` to a real domain with valid DNS."
        echo "- Enable HTTPS (all backends above do so by default)."
        echo "- Restrict sensitive service ports at the firewall level."
        echo "- Do not expose admin UIs (Portainer, Dashy) without authentication."
    } > "${out}"
    info "Written: ${out#"${REPO_ROOT}/"}"
}

# ─── Dispatch ─────────────────────────────────────────────────────────────────
echo -e "\n${BOLD}Generating ${BACKEND} configuration …${RESET}"
case "${BACKEND}" in
    godoxy)  generate_godoxy ;;
    traefik) generate_traefik ;;
    caddy)   generate_caddy ;;
esac

generate_doc

echo -e "\n${GREEN}Done.${RESET} Backend: ${BACKEND} | ${count} service(s) configured."
