# ADGUARD HOME
# GitHub: https://github.com/AdguardTeam/AdGuardHome
# Image: adguard/adguardhome
# Docs: https://adguard-dns.io/kb/adguard-home/overview/
#
# Network-wide ad and tracker blocking DNS server. Acts as a DNS server for your
# entire network and blocks ads, tracking, and malware at the DNS level.

services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    restart: unless-stopped

    environment:
      - TZ=${TZ}

    volumes:
      - ${DOCKER_DATA}/networking/adguard/work:/opt/adguardhome/work
      - ${DOCKER_DATA}/networking/adguard/config:/opt/adguardhome/conf

    ports:
      - ${PORT_ADGUARD_SETUP:-3000}:3000                       # Initial setup web UI
      - ${PORT_ADGUARD_HTTP:-80}:80                            # Web UI after setup
      - ${PORT_ADGUARD_HTTPS:-443}:443                         # HTTPS web UI
      - ${PORT_ADGUARD_DNS:-53}:53/tcp                         # DNS over TCP
      - ${PORT_ADGUARD_DNS:-53}:53/udp                         # DNS over UDP
      # - 853:853/tcp                                          # DNS over TLS
      # - 784:784/udp                                          # DNS over QUIC
      # - 67:67/udp                                            # DHCP server

    # networks:
    #   - ${DEFAULT_NETWORK}
